# Usecase configuration for Xiaomi Lemon
# Author: Adam Skladowski <a39.skl@gmail.com>

SectionVerb {

	EnableSequence [
		cset "name='RX_CODEC_DMA_RX_0 Audio Mixer MultiMedia1' 1"
		cset "name='MultiMedia2 Mixer VA_CODEC_DMA_TX_0' 1"
		cset "name='MultiMedia3 Mixer TX_CODEC_DMA_TX_3' 1"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Speaker playback"

	Include.wcdauxe.File "/codecs/wcd937x/AuxEnableSeq.conf"
	Include.wcdauxd.File "/codecs/wcd937x/AuxDisableSeq.conf"
	Include.rxmauxe.File "/codecs/qcom-lpass/rx-macro/AuxEnableSeq.conf"
        Include.rxmauxd.File "/codecs/qcom-lpass/rx-macro/AuxDisableSeq.conf"

	Value {
		PlaybackPriority 300
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixer "default:${CardId}"
		PlaybackMixerElem "Speakers"
	}
}

SectionDevice."Earpiece" {
	Comment "Earpiece playback"

	Include.wcdeare.File "/codecs/wcd937x/EarpieceEnableSeq.conf"
	Include.wcdeard.File "/codecs/wcd937x/EarpieceDisableSeq.conf"
	Include.rxmeare.File "/codecs/qcom-lpass/rx-macro/EarpieceEnableSeq.conf"
        Include.rxmeard.File "/codecs/qcom-lpass/rx-macro/EarpieceDisableSeq.conf"

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixer "default:${CardId}"
		PlaybackMixerElem "Earpiece"
	}
}

SectionDevice."Headphones" {
	Comment "Headphones playback"

	Include.wcdhpe.File "/codecs/wcd937x/HeadphoneEnableSeq.conf"
	Include.wcdhpd.File "/codecs/wcd937x/HeadphoneDisableSeq.conf"
	Include.rxmhpe.File "/codecs/qcom-lpass/rx-macro/HeadphoneEnableSeq.conf"
        Include.rxmhpd.File "/codecs/qcom-lpass/rx-macro/HeadphoneDisableSeq.conf"

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixer "default:${CardId}"
		PlaybackMixerElem "HP"
	}
}

